### ISSUE TITLE
Do you support mouse absolute coordinate mode.

### ISSUE THREAD

**Issue by zuozhehao** [yijenlu1971/esp_hid_device#1]
Do you support mouse absolute coordinate mode

**Comment by yijenlu1971** [comment]
No.
The pointer is relative.

**Comment by zuozhehao** [comment]
> No.
> The pointer is relative.

okay, thank you.

Do you know how to get hid reports of the equipment?

I have a small device that can move in absolute coordinates, but I don't know the HID report it uses

**Comment by yijenlu1971** [comment]
> 
> Do you know how to get hid reports of the equipment?
> I have a small device that can move in absolute coordinates, but I don't know the HID report it uses

Check "hid_device_le_prf.c" in code, which creates HidReport.
You may change the structure of HID report.  
The report ID = 1 represents pointer (mouse), the value of X, Y, Wheel are relative.

**Comment by zuozhehao** [comment]
> > Do you know how to get hid reports of the equipment?
> > I have a small device that can move in absolute coordinates, but I don't know the HID report it uses
> 
> Check "hid_device_le_prf.c" in code, which creates HidReport.
> You may change the structure of HID report.
> The report ID = 1 represents pointer (mouse), the value of X, Y, Wheel are relative.

OK, thank you for your reply.

Is there a recommended tool to get HID report descriptor of my device.

**Comment by yijenlu1971** [comment]
I have no idea to get HID descriptor.  Wireshark may capture USB device, but I can't capture it on BLE.

**Comment by zuozhehao** [comment]
> I have no idea to get HID descriptor. Wireshark may capture USB device, but I can't capture it on BLE.

OK, thank you for your reply
