### ISSUE TITLE
Why doesn't this example work on windows?

### ISSUE THREAD

**Issue by Krzymr** [yijenlu1971/esp_hid_device#2]
I upload the code to ESP and connect it to the PC but there is no reaction (I have recommended the keyboard and volume control functions) in the terminal, I can see that the loop is running. When I connect ESP with android everything works as it should. What do I need to do to make this example work on a Win 10 PC?

**Comment by yijenlu1971** [comment]
[https://youtu.be/VkRo0fu53F4](url)  This is my procedure on Win10, only mouse pointer.
In this code, I marked out keyboard and vol control. If you want the functions, you should implement by "esp_hidd_send_keyboard_value" and "esp_hidd_send_consumer_value"

**Comment by Krzymr** [comment]
I'm using functions
"uint8_t key_vaule = {HID_KEY_A};
esp_hidd_send_keyboard_value (hid_conn_id, 0, & key_vaule, 1); "
does not work when I connect to windows 10.

**Comment by yijenlu1971** [comment]
Open notepad, the key may be printed out. I tested that.

**Comment by Krzymr** [comment]
ok. sorry for the problem. 
In bluetooth settings I removed this device and added it again and now it works as it should.
Thanks for help.
